### ISSUE TITLE
SCEP docs

### ISSUE THREAD

**Issue by pegahnikbakht** [smallstep/scep#15]
Hi,

Where I can find some documentation example on how to start a SCEP server and send requests with client? 
I added SCEP provisioner in step-ca according to the documentations here [https://smallstep.com/docs/step-ca/provisioners/#scep](url) but how to send CSR to the provisioner and get a signed cert with SCEP? 

Thanks for the help,
Pegah

**Comment by hslatman** [comment]
Hi @pegahnikbakht, our main documentation for SCEP is indeed at https://smallstep.com/docs/step-ca/provisioners/#scep. Configuration of a SCEP client largely depends on the specific client you're using, and is outside the scope of our CA, so that's why we haven't documented that part specifically.

Example clients:

- [sscep](https://github.com/certnanny/sscep). They have documentation on how to use the CLI in their [README](https://github.com/certnanny/sscep/blob/master/README.md).
- MicroMDM [scepclient](https://github.com/micromdm/scep/tree/main/cmd/scepclient), which uses this package. Client usage is explained [here](https://github.com/micromdm/scep?tab=readme-ov-file#client-usage).

There are other SCEP clients too, but those two are relatively simple to get started with and try out our SCEP support. In general you'll want to check if there's already a SCEP client on the system you're trying to use it with. For example, on macOS and Windows there are SCEP clients that are used when an MDM solution pushes a SCEP configuration.

In general the configuration of the SCEP client comes down to the [CA URL / SCEP endpoint](https://smallstep.com/docs/step-ca/provisioners/#scep), the CA fingerprint (optional, but good to have), the requested certificate contents (e.g. SANs, Common Name, etc.), and possibly additional server trust settings.

**Comment by pegahnikbakht** [comment]
@hslatman Hi again, 
I have setup a SCEP provisioner (running on port 8443) and a SCEP webhook (on port 9443), and I try to do the enrollment with sscep with the following command:
```
./sscep enroll -u https://127.0.0.1:8443/scep/my_scep_provisioner -c ca.crt -k local.key -r local.csr -l local.crt

```
But I get an error that the URL is illegal, which URL should be used when we are using https and webhook?

**Comment by hslatman** [comment]
@pegahnikbakht in the SSCEP project they've made the choice to not support SCEP via HTTPS, and to mark those URLs as "illegal": https://github.com/certnanny/sscep/issues/142.

A quick workaround is to use the `insecureAddress` configuration to expose the SCEP provisioner via HTTP. That'll work with SSCEP and other clients. 

In real deployments, SCEP is often exposed via HTTPS. It works, but there are caveats with it.

**Comment by pegahnikbakht** [comment]
@hslatman ok then for the SCEP webhook should I run it on a http port for example 8081? instead of 9443?

**Comment by hslatman** [comment]
@pegahnikbakht the webhook can run on HTTPS. I believe we even enforce that. Ensure that you configure it with a cert chaining to a root that the CA trusts, for example by issuing one from the CA itself.

**Comment by pegahnikbakht** [comment]
But when I use provisioner on http as: `./sscep enroll -u http://127.0.0.1:8080/scep/my_scep_provisioner -c ca.crt -k local.key -r local.csr -l local.crt` and webhook running on https, I get this error on provisioner logs: 

```
error="webhook server did not allow request" fields.time="2024-08-08T10:10:06+02:00" method=POST name=ca path="/scep/my_scep_provisioner?operation=PKIOperation"

```

**Comment by hslatman** [comment]
Well, the webhook is the one validating the challenge, and will thus make the decision whether or not to allow the request. This result depends on the implementation of the webhook. It should return `{"allow": true}` at the minimum for the CA to consider the challenge to be OK.

**Comment by pegahnikbakht** [comment]
How I can debug it to find out the problem, since I'm quite sure the challenge is correct!

**Comment by hslatman** [comment]
That depends on how your webhook server is implemented and where it is hosted. I would start with dumping the incoming request, and verifying the contents. An example can be found here: https://github.com/hslatman/scep-webhook-validator/.

**Comment by pegahnikbakht** [comment]
I'm using this webhook from smallstep [https://github.com/smallstep/webhooks.git](url)
And followed this instruction to set it up: https://smallstep.com/docs/step-ca/webhooks/#implementation-details

**Comment by hslatman** [comment]
You'll need to adapt it to ensure it supports the SCEP challenge, and that it does the right thing for your system. It's just an example; not a ready-to-deploy system.

**Comment by pegahnikbakht** [comment]
So this webhook [https://github.com/smallstep/webhooks](url) does not support SCEP challenge by default?

**Comment by pegahnikbakht** [comment]
Do you have any valid SCEP webhook for testing?

**Comment by hslatman** [comment]
https://github.com/hslatman/scep-webhook-validator/

**Comment by pegahnikbakht** [comment]
Why the ACME provisioner is required to test the SCEP webhook?

**Comment by hslatman** [comment]
As mentioned in the documentation for the example server:

```text
The example uses the step-ca ACME directory at https://127.0.0.1:8443/acme/acme/directory 
to request a certificate, because all webhook servers must use HTTPS. The root can be provided 
to point the root of step-ca instance, so that when the built-in ACME client connects to the server, 
the HTTPS connection will be trusted.
```

In short, it's a quick and easy way for the webhook receiver to obtain a certificate. You can provide it in another way if you want. And to reiterate: these are just examples. We don't know what your requirements are in terms of validating the challenge, so it is likely you'll need to make changes to the example code to make it work in your use case.
